name: Auto

on:
  schedule:
    - cron: '0 8 * * *'   # JST 17:00
    - cron: '0 9 * * *'   # JST 18:00
    - cron: '30 9 * * *'  # JST 18:30
    - cron: '0 10 * * *'  # JST 19:00
    - cron: '30 10 * * *' # JST 19:30
    - cron: '0 11 * * *'  # JST 20:00
    - cron: '30 11 * * *' # JST 20:30
    - cron: '0 12 * * *'  # JST 21:00
  workflow_dispatch:

env:
  DIFY_TOKENS: ${{ secrets.DIFY_TOKENS }}
  DIFY_BASE_URL: ${{ secrets.DIFY_BASE_URL }}
  DIFY_INPUTS: ${{ secrets.DIFY_INPUTS }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
  AIBOTK_KEY: ${{ secrets.AIBOTK_KEY }}
  AIBOTK_ROOM_RECIVER: ${{ secrets.AIBOTK_ROOM_RECIVER }}
  AIBOTK_CONTACT_RECIVER: ${{ secrets.AIBOTK_CONTACT_RECIVER }}

jobs:
  DifyWorkflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          yarn
          yarn workflowDify
